In [1]:
# reshape

# Array 의 shape 크기를 변경함, elements 의 갯수는 동일

In [2]:
import numpy as np

In [3]:
test_matrix = [[1, 2, 3, 4], [1, 2, 5, 8]]
np.array(test_matrix).shape

(2, 4)

In [4]:
np.array(test_matrix).reshape(8,)

array([1, 2, 3, 4, 1, 2, 5, 8])

In [5]:
np.array(test_matrix).reshape(8,).shape

(8,)

In [6]:
# -1 : size를 기반으로 row 개수 선정
np.array(test_matrix).reshape(-1, 2).shape

(4, 2)

In [7]:
np.array(test_matrix).reshape(2, 2, 2)

array([[[1, 2],
        [3, 4]],

       [[1, 2],
        [5, 8]]])

In [8]:
np.array(test_matrix).reshape(2, -1, 2).shape

(2, 2, 2)

In [9]:
# test_matrix 는 할당이 안되었기 때문에 변경 X
test_matrix

[[1, 2, 3, 4], [1, 2, 5, 8]]

In [10]:
# flatten : 다차원 array를 1차원 array로 변환

In [11]:
test_matrix = [[[1,2,3,4], [1,2,5,8]], [[1,2,3,4], [1,2,5,8]]]
np.array(test_matrix)

array([[[1, 2, 3, 4],
        [1, 2, 5, 8]],

       [[1, 2, 3, 4],
        [1, 2, 5, 8]]])

In [12]:
np.array(test_matrix).flatten()

array([1, 2, 3, 4, 1, 2, 5, 8, 1, 2, 3, 4, 1, 2, 5, 8])

In [13]:
# indexing & slicing

In [14]:
# indexing for numpy array

# list 와 달리 이차원 배열에서 [0,0] 표기법 제공
# matrix 일 경우 앞은 row, 뒤는 column 을 의미

In [15]:
a = np.array([[1, 2, 3], [4.5, 5, 6]], int)
print(a)
print(a[0,0]) # Two dimensional array represintation 1
print(a[0][0]) # Two dimensional array represintation 2

[[1 2 3]
 [4 5 6]]
1
1


In [16]:
a[0,0] = 12 # Matrix 0,0 에 12 할당
print(a)

[[12  2  3]
 [ 4  5  6]]


In [17]:
a[0][0] = 5 # Matrix 0,0 에 5 할당
print(a)

[[5 2 3]
 [4 5 6]]


In [18]:
# slicing for numpy array

# list 와 달리 행과 열 부분을 나눠서 slicing 이 가능함
# matrix 의 부분집합을 추출할 때 유용

In [19]:
a = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]], int)

In [20]:
a[ : , 2: ] # 전체 Row 의 2열 이상 

array([[ 3,  4,  5],
       [ 8,  9, 10]])

In [21]:
a[1, 1:3] # 1 Row 의 1 ~ 2열

array([7, 8])

In [22]:
a[1:3] # 1 Row ~ 2 Row 의 전체

array([[ 6,  7,  8,  9, 10]])

In [23]:
test_example = np.array([
    [1, 2, 5, 8], [1, 2, 5, 8], [1, 2, 5, 8], [1, 2, 5, 8]], int)

In [24]:
test_example[ :2, : ] # Row 0 ~ 1 까지, column 전체

array([[1, 2, 5, 8],
       [1, 2, 5, 8]])

In [25]:
test_example[:, 1:3].shape

(4, 2)

In [26]:
test_example[1:2, :2]

array([[1, 2]])

In [27]:
a = np.arange(100).reshape(10, 10)
a

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [28]:
a[:, -1]

array([ 9, 19, 29, 39, 49, 59, 69, 79, 89, 99])

In [29]:
a = np.arange(15).reshape(3,-1)
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [30]:
a[:, : :2] # 건너뛰기 : 열 2칸씩 뛰기

array([[ 0,  2,  4],
       [ 5,  7,  9],
       [10, 12, 14]])

In [31]:
a[ : :2, : :3] # 행 2칸 건너뛰기, 행 3칸 건너뛰기

array([[ 0,  3],
       [10, 13]])

In [32]:
# Creation funtion

In [33]:
# arange

# array의 볌위를 지정하여, 값의 list를 생성하는 명령어

In [34]:
np.arange(30) # arange : list 의 range 와 같은 효과

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [35]:
np.arange(0, 5, 0.5) # 시작, 끝, 스텝, # floating point 도 표시 가능

array([0. , 0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5])

In [36]:
np.arange(30).reshape(5, 6)

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29]])

In [37]:
# zeros

# 0 으로 가득찬 ndarray 생성

In [38]:
np.zeros(shape=(10,), dtype=np.int8) # 10 - zero vector 생성

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0], dtype=int8)

In [39]:
np.zeros((2, 5)) # 2 by 5 

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [40]:
# ones

# 1로 가득찬 ndarray 생성

In [41]:
np.ones(shape=(10,), dtype=np.int8)

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1], dtype=int8)

In [42]:
np.ones((2, 5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [43]:
# empty 

# shape 만 주어지고 비어있는 ndarray 생성
# memory initializition 이 되지 않음

In [44]:
np.empty(shape=(10,), dtype=np.int8)

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1], dtype=int8)

In [45]:
np.empty((3, 5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [46]:
# something_like

# 기존 ndarray 의 shape 크기 만큼 1, 0, empty array 를 반환

In [47]:
test_matrix = np.arange(30).reshape(5, 6)
np.ones_like(test_matrix)

array([[1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1]])

In [ ]:
# identity

# 단위 행렬(i 행렬)을 생성함

In [48]:
np.identity(n=3, dtype=np.int8)

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]], dtype=int8)

In [49]:
np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [50]:
# eye

# 대각선이 1 인 행렬, k값의 시작 index의 변경이 가능

In [51]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [52]:
np.eye(3, 5, k=2)

array([[0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [53]:
np.eye(N=3, M=5, dtype=np.int8)

array([[1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0]], dtype=int8)

In [ ]:
# diag

# 대각 행렬의 값을 추출함

In [54]:
matrix = np.arange(9).reshape(3, 3)
np.diag(matrix)

array([0, 4, 8])

In [55]:
np.diag(matrix, k=1) # k : start index

array([1, 5])

In [56]:
# random sampling

# 데이터 분포에 따른 sampling 으로 array를 생성

In [57]:
np.random.uniform(0, 1, 10).reshape(2, 5) # 균등분포

array([[0.52616779, 0.58684463, 0.93700291, 0.77924388, 0.9050208 ],
       [0.58416878, 0.48626016, 0.86267884, 0.67126489, 0.12427413]])

In [58]:
np.random.normal(0, 1, 10).reshape(2, 5) # 정규분포

array([[-0.12644181, -1.13579763, -0.56641753,  0.56699114, -2.55509443],
       [ 0.37295465, -0.5600972 , -0.00648065, -0.15251241, -1.29685726]])

In [59]:
# operation fundions

In [60]:
# sum

# ndarray의 element들 간의 합을 구함, list 의 sum 기능과 동일

In [61]:
test_array = np.arange(1, 11)
test_array

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [63]:
test_array.sum(dtype=np.float32)

55.0

In [64]:
# axis

# 모든 operation function을 샐행할 때 기준이 되는 dimension 축

In [65]:
test_array = np.arange(1, 13).reshape(3, 4)
test_array

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [66]:
test_array.sum(axis=1), test_array.sum(axis=0)

(array([10, 26, 42]), array([15, 18, 21, 24]))

In [72]:
third_order_tensor = np.array([test_array, test_array, test_array])
third_order_tensor

array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]],

       [[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]],

       [[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]]])

In [73]:
third_order_tensor.sum(axis=2)

array([[10, 26, 42],
       [10, 26, 42],
       [10, 26, 42]])

In [74]:
third_order_tensor.sum(axis=1)

array([[15, 18, 21, 24],
       [15, 18, 21, 24],
       [15, 18, 21, 24]])

In [75]:
third_order_tensor.sum(axis=0)

array([[ 3,  6,  9, 12],
       [15, 18, 21, 24],
       [27, 30, 33, 36]])

In [ ]:
# mean & std

# mathematical funtions

In [76]:
# concatenate

# numpy array 를 합치는(붙이는) 함수

In [77]:
a = np.array([1, 2, 3])
b = np.array([2, 3, 4])
np.vstack((a, b))

array([[1, 2, 3],
       [2, 3, 4]])

In [78]:
a = np.array([[1], [2], [3]])
b = np.array([[2], [3], [4]])
np.hstack((a, b))

array([[1, 2],
       [2, 3],
       [3, 4]])

In [81]:
a = np.array([[1, 2, 3]])
b = np.array([[2, 3, 4]])
np.concatenate((a, b), axis=0)

array([[1, 2, 3],
       [2, 3, 4]])

In [82]:
a = np.array([[1, 2], [3, 4]])
b = np.array([[5], [6]])
np.concatenate((a, b), axis=1)

array([[1, 2, 5],
       [3, 4, 6]])

In [86]:
# newaxis : 하나의 축을 추가
a = np.array([[1, 2], [3, 4]])
b = np.array([5, 6])

In [87]:
b = b[np.newaxis, :]
np.concatenate((a, b.T), axis=1)

array([[1, 2, 5],
       [3, 4, 6]])

In [88]:
# array operation

# numpy는 array 간의 기본적인 사칙 연산을 지원함

In [89]:
test_a = np.array([[1, 2, 3], [4, 5, 6]], float)

In [90]:
test_a + test_a # matrix + matrix 연산

array([[ 2.,  4.,  6.],
       [ 8., 10., 12.]])

In [91]:
test_a - test_a # matrix - matrix 연산

array([[0., 0., 0.],
       [0., 0., 0.]])

In [92]:
test_a * test_a # matrix 내 같은 위치에 있는 값 끼리 연산

array([[ 1.,  4.,  9.],
       [16., 25., 36.]])

In [93]:
# Dot Product

# Matrix 의 기본 연산, dot함수 사용

In [94]:
test_a = np.arange(1, 7).reshape(2, 3)
test_b = np.arange(7, 13).reshape(3, 2)

In [95]:
test_a.dot(test_b)

array([[ 58,  64],
       [139, 154]])

In [ ]:
# transpose 전치행렬

# transpose 또는 T arrtibute 사용

In [96]:
test_a.transpose()

array([[1, 4],
       [2, 5],
       [3, 6]])

In [97]:
test_a.T.dot(test_a)

array([[17, 22, 27],
       [22, 29, 36],
       [27, 36, 45]])

In [98]:
test_a.T

array([[1, 4],
       [2, 5],
       [3, 6]])

In [99]:
# broadcastiong

# shape 이 다른 배열 간 연산을 지원하는 기능

In [100]:
test_matrix = np.array([[1, 2, 3], [4, 5, 6]], float)
scalar = 3

In [101]:
test_matrix + scalar # matrix - scalar 덧셈

array([[4., 5., 6.],
       [7., 8., 9.]])

In [102]:
test_matrix - scalar

array([[-2., -1.,  0.],
       [ 1.,  2.,  3.]])

In [103]:
test_matrix = np.arange(1, 13).reshape(4, 3)
test_vector = np.arange(10, 40, 10)
test_matrix + test_vector

array([[11, 22, 33],
       [14, 25, 36],
       [17, 28, 39],
       [20, 31, 42]])

In [104]:
# numpy performance # 1

# timeit 

# jupyter 환경에서 코드의 퍼포먼스를 체크하는 함수

In [107]:
def sclar_vector_product(scalar, vector):
    result = []

    for value in vector:
        result.append(scalar * value)

    return result

iternation_max = 100000000

vector = list(range(iternation_max))
scalar = 2

In [110]:
%timeit sclar_vector_product(scalar, vector) # for loop을 이용한 성능

10.5 s ± 170 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


In [109]:
%timeit [scalar * value for value in range(iternation_max)]
# list comprehension을 이용한 성능

8.47 s ± 143 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


In [108]:
%timeit np.arange(iternation_max) * scalar # numpy를 이용한 성능

305 ms ± 10.6 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)
