In [ ]:
# ndarray

In [1]:
import numpy as np

In [3]:
# np.array 함수를 활용하여 배열(ndarray 객체) 생성, dtype=float
test_array = np.array([1, 4, 5, 8], float)
print(test_array)
type(test_array[3])

[1. 4. 5. 8.]


numpy.float64

In [4]:
a = [1, 2, 3, 4, 5]
b = [5, 4, 3, 2, 1]

In [5]:
a = np.array(a, int)
a

array([1, 2, 3, 4, 5])

In [6]:
test_array = np.array(["1", "4", 5 , 8], float)
test_array

array([1., 4., 5., 8.])

In [8]:
type(test_array)

numpy.ndarray

In [7]:
type(test_array[3])

numpy.float64

In [9]:
a = [1, 2, 3, 4, 5]
b = [5, 4, 3, 2, 1]
a[0] is b[-1]

True

In [10]:
a = np.array(a)
b = np.array(b)
a[0] is b[-1]

False

In [11]:
# shape : numpy array 의 dimension 구성 반환
# dtype : numpy array 의 데이터 type 을 반환

print(test_array)
print(type(test_array[3]))
print(test_array.dtype)
print(test_array.shape)

[1. 4. 5. 8.]
<class 'numpy.float64'>
float64
(4,)


In [13]:
c = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]
np.array(c).shape

(3, 3)

In [15]:
# nbytes : ndarray object 의 메모리 크기 반환

np.array([[1, 2, 3], [4.5, "5", "6"]], dtype=np.float32).nbytes

24

In [16]:
np.array([[1, 2, 3], [4.5, "5", "6"]], dtype=np.int8).nbytes

6

In [17]:
np.array([[1, 2, 3], [4.5, "5", "6"]], dtype=np.float64).nbytes

48