In [1]:
# reshape

# Array 의 shape 크기를 변경함, elements 의 갯수는 동일

In [3]:
import numpy as np

In [4]:
test_matrix = [[1, 2, 3, 4], [1, 2, 5, 8]]
np.array(test_matrix).shape

(2, 4)

In [5]:
np.array(test_matrix).reshape(8,)

array([1, 2, 3, 4, 1, 2, 5, 8])

In [6]:
np.array(test_matrix).reshape(8,).shape

(8,)

In [7]:
# -1 : size를 기반으로 row 개수 선정
np.array(test_matrix).reshape(-1, 2).shape

(4, 2)

In [8]:
np.array(test_matrix).reshape(2, 2, 2)

array([[[1, 2],
        [3, 4]],

       [[1, 2],
        [5, 8]]])

In [9]:
np.array(test_matrix).reshape(2, -1, 2).shape

(2, 2, 2)

In [11]:
# test_matrix 는 할당이 안되었기 때문에 변경 X
test_matrix

[[1, 2, 3, 4], [1, 2, 5, 8]]

In [12]:
# flatten : 다차원 array를 1차원 array로 변환

In [15]:
test_matrix = [[[1,2,3,4], [1,2,5,8]], [[1,2,3,4], [1,2,5,8]]]
np.array(test_matrix)

array([[[1, 2, 3, 4],
        [1, 2, 5, 8]],

       [[1, 2, 3, 4],
        [1, 2, 5, 8]]])

In [16]:
np.array(test_matrix).flatten()

array([1, 2, 3, 4, 1, 2, 5, 8, 1, 2, 3, 4, 1, 2, 5, 8])

In [ ]:
# indexing & slicing

In [ ]:
# indexing for numpy array

# list 와 달리 이차원 배열에서 [0,0] 표기법 제공
# matrix 일 경우 앞은 row, 뒤는 column 을 의미

In [17]:
a = np.array([[1, 2, 3], [4.5, 5, 6]], int)
print(a)
print(a[0,0]) # Two dimensional array represintation 1
print(a[0][0]) # Two dimensional array represintation 2

[[1 2 3]
 [4 5 6]]
1
1


In [18]:
a[0,0] = 12 # Matrix 0,0 에 12 할당
print(a)

[[12  2  3]
 [ 4  5  6]]


In [19]:
a[0][0] = 5 # Matrix 0,0 에 5 할당
print(a)

[[5 2 3]
 [4 5 6]]


In [21]:
# slicing for numpy array

# list 와 달리 행과 열 부분을 나눠서 slicing 이 가능함
# matrix 의 부분집합을 추출할 때 유용

In [26]:
a = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]], int)

In [30]:
a[ : , 2: ] # 전체 Row 의 2열 이상 

array([[ 3,  4,  5],
       [ 8,  9, 10]])

In [31]:
a[1, 1:3] # 1 Row 의 1 ~ 2열

array([7, 8])

In [32]:
a[1:3] # 1 Row ~ 2 Row 의 전체

array([[ 6,  7,  8,  9, 10]])

In [34]:
test_example = np.array([
    [1, 2, 5, 8], [1, 2, 5, 8], [1, 2, 5, 8], [1, 2, 5, 8]], int)

In [35]:
test_example[ :2, : ] # Row 0 ~ 1 까지, column 전체

array([[1, 2, 5, 8],
       [1, 2, 5, 8]])

In [36]:
test_example[:, 1:3].shape

(4, 2)

In [37]:
test_example[1:2, :2]

array([[1, 2]])

In [38]:
a = np.arange(100).reshape(10, 10)
a

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [39]:
a[:, -1]

array([ 9, 19, 29, 39, 49, 59, 69, 79, 89, 99])

In [42]:
a = np.arange(15).reshape(3,-1)
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [45]:
a[:, : :2] # 건너뛰기 : 열 2칸씩 뛰기

array([[ 0,  2,  4],
       [ 5,  7,  9],
       [10, 12, 14]])

In [46]:
a[ : :2, : :3] # 행 2칸 건너뛰기, 행 3칸 건너뛰기

array([[ 0,  3],
       [10, 13]])

In [47]:
# Creation funtion

In [ ]:
# arange

# array의 볌위를 지정하여, 값의 list를 생성하는 명령어

In [48]:
np.arange(30) # arange : list 의 range 와 같은 효과

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [49]:
np.arange(0, 5, 0.5) # 시작, 끝, 스텝, # floating point 도 표시 가능

array([0. , 0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5])

In [50]:
np.arange(30).reshape(5, 6)

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29]])

In [51]:
# zeros

# 0 으로 가득찬 ndarray 생성

In [52]:
np.zeros(shape=(10,), dtype=np.int8) # 10 - zero vector 생성

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0], dtype=int8)

In [53]:
np.zeros((2, 5)) # 2 by 5 

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [54]:
# ones

# 1로 가득찬 ndarray 생성

In [55]:
np.ones(shape=(10,), dtype=np.int8)

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1], dtype=int8)

In [56]:
np.ones((2, 5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [57]:
# empty 

# shape 만 주어지고 비어있는 ndarray 생성
# memory initializition 이 되지 않음

In [60]:
np.empty(shape=(10,), dtype=np.int8)

array([-128,   27,   82,  -49,   79,    2,    0,    0,    0,    0],
      dtype=int8)

In [61]:
np.empty((3, 5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [62]:
# something_like

# 기존 ndarray 의 shape 크기 만큼 1, 0, empty array 를 반환

In [63]:
test_matrix = np.arange(30).reshape(5, 6)
np.ones_like(test_matrix)

array([[1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1]])