In [1]:
# comparisions

In [4]:
import numpy as np

In [5]:
# All & Any

# Array 의 데이터 전부(and) 또는 일부(or) 가 조건에 만족 여부 반환

In [6]:
a = np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [7]:
# any : 하나라도 만족하면 True

np.any(a > 5), np.any(a < 0)

(True, False)

In [8]:
# all : 모두 만족해야 True

np.all(a > 5), np.all(a < 10)

(False, True)

In [9]:
a < 4 # boolean array 가 나온다

array([ True,  True,  True,  True, False, False, False, False, False,
       False])

In [10]:
# comparision operation 1

# numpy는 배열의 크기가 동일할 때 element 간 비교의 결과를 Boolean 으로 반환

In [11]:
test_a = np.array([1, 3, 0], float)
test_b = np.array([5, 2, 0], float)
test_a > test_b

array([False,  True, False])

In [12]:
test_a == test_b

array([False, False,  True])

In [14]:
(test_a > test_b).any() # any : 하나라도 true 이면 true

True

In [15]:
# comparision operation 2

In [16]:
a = np.array([1, 3, 0], float)
np.logical_and(a > 0, a < 3) # and 조건

array([ True, False, False])

In [17]:
b = np.array([True, False, True], bool)
np.logical_not(b) # Not 조건

array([False,  True, False])

In [18]:
c = np.array([False, True, False], bool)
np.logical_or(b, c) # OR 조건

array([ True,  True,  True])

In [ ]:
# np.where

In [28]:
np.where(a > 0, 3, 2) # where(condition, True, False)

array([3, 2, 3])

In [29]:
a = np.arange(10)
np.where(a > 5) # index 값 반환

(array([6, 7, 8, 9], dtype=int64),)

In [30]:
a = np.array([1, np.NaN, np.Inf], float)
np.isnan(a) # Not a Number

array([False,  True, False])

In [31]:
np.isfinite(a) # is finite number : 발산하는 값

array([ True, False, False])

In [32]:
# argmax & argmin

# array 내 최대값 또는 최소값의 index 를 반환

In [40]:
a = np.array([1, 2, 4, 5, 8, 78, 23, 3])
np.argmax(a), np.argmin(a)

(5, 0)

In [41]:
a.argsort()

array([0, 1, 7, 2, 3, 4, 6, 5], dtype=int64)

In [42]:
a.argsort()[::-1]

array([5, 6, 4, 3, 2, 7, 1, 0], dtype=int64)

In [43]:
# axis 기반의 반환
a = np.array([[1, 2, 4, 7], [9, 88, 6, 45], [9, 76, 3, 4]])
np.argmax(a, axis=1), np.argmin(a, axis=0)

(array([3, 1, 1], dtype=int64), array([0, 0, 2, 2], dtype=int64))

In [44]:
# boolean & fancy index

In [45]:
# boolean index

# 특정 조건에 따른 값을 배열 형태로 추출
# Comparison operation 함수들도 모두 사용 가능

In [46]:
test_array = np.array([1, 4, 0, 2, 3, 8, 9, 7], float)
test_array > 3

array([False,  True, False, False, False,  True,  True,  True])

In [47]:
test_array[test_array > 3] # 조건이 True 인 index 의 element 만 추출

array([4., 8., 9., 7.])

In [54]:
test_array.shape

(8,)

In [53]:
(test_array > 3).shape # test_array.shape 와 동일

(8,)

In [49]:
condition = test_array < 3
test_array[condition]

array([1., 0., 2.])

In [55]:
# fancy index

# numpy 는 array를 index value 로 사용해서 값 추출

In [56]:
a = np.array([2, 4, 6, 8], float)
b = np.array([0, 0, 1, 3, 2, 1], int) # 반드시 interger 로 선언
a[b] # bracket index, b 배열의 값을 index로 하여 a 값들을 추출

array([2., 2., 4., 8., 6., 4.])

In [57]:
a.take(b) # take 함수: bracket index 와 같은 효과

array([2., 2., 4., 8., 6., 4.])

In [58]:
# matrix 형태의 데이터도 가능

a = np.array([[1, 4], [9, 16]], float)
b = np.array([0, 0, 1, 1, 0], int)
c = np.array([0, 1, 1, 1, 1], int)
a[b, c] # b : row index, c : column index

array([ 1.,  4., 16., 16.,  4.])

In [ ]:
# numpy data I/O

In [ ]:
# loadtext 

# csv 타입의 파일을 읽어오는 함수

In [ ]:
# npy 확장명으로 많이 저장한다