In [2]:
# 텐서 조작하기(Tensor Manipulation)
# 벡터, 행렬, 텐서의 개념에 대해 이해
# numpy와 pytorch로 벡터, 행렬, 텐서를 다루는 방법에 대해 이해

In [3]:
# Numpy로 텐서 만들기(벡터와 행렬 만들기)
import numpy as np

In [4]:
# 1. 1D with Numpy
# 넘파이로 1차원 텐서인 벡터 생성해보기

t = np.array([0., 1., 2., 3., 4., 5., 6.])
print(t)

[0. 1. 2. 3. 4. 5. 6.]


In [5]:
# 1차원 텐서인 벡터의 차원과 크기를 출력
print('Rank of t: ', t.ndim) # ndim : 몇 차원인지 출력
print('Shape of t: ', t.shape) # shape : 크기 출력 ; (7,) = (1, 7) 을 의미

Rank of t:  1
Shape of t:  (7,)


In [6]:
# Numpy 기초 이해하기
# Numpy에서 각 벡터의 원소에 접근하는 방법 알아보기

print('t[0] t[1] t[-1] = ', t[0], t[1], t[-1]) # 인덱스를 이용한 접근

t[0] t[1] t[-1] =  0.0 1.0 6.0


In [7]:
# 슬라이싱을 이용한 접근
print('t[2:5] t[4:-1] = ', t[2:5], t[4:-1] )

t[2:5] t[4:-1] =  [2. 3. 4.] [4. 5.]


In [8]:
# 시작번호 끝 번호 생략
print('t[:2] t[3:] = ', t[:2], t[3:])

t[:2] t[3:] =  [0. 1.] [3. 4. 5. 6.]


In [9]:
# 2D with Numpy
# Numpy로 2차원 행렬 만들어보기

t = np.array([[1., 2., 3.], [4., 5., 6.], [7., 8., 9.], [10., 11., 12.]])
print(t)

[[ 1.  2.  3.]
 [ 4.  5.  6.]
 [ 7.  8.  9.]
 [10. 11. 12.]]


In [10]:
print('Rank of t : ', t.ndim)
print('Shape of t : ', t.shape)

Rank of t :  2
Shape of t :  (4, 3)


In [11]:
# 파이토치 텐서 선언하기
# 파이토치는 Numpy와 유사
import torch

In [12]:
# 1D with Pytorch
# 파이토치로 1차원 텐서인 벡터 생성해보기
t = torch.FloatTensor([0., 1., 2., 3., 4., 5., 6.])
print(t)

tensor([0., 1., 2., 3., 4., 5., 6.])


In [13]:
# dim을 사용하면 현재 텐서의 차원을 보여준다. shape나 size()를 사용하면 크기를 확인할 수 있다
print(t.dim()) # rank, 차원
print(t.shape)
print(t.size())

1
torch.Size([7])
torch.Size([7])


In [14]:
# 인덱스 및 슬라이싱 접근
print(t[0], t[1], t[-1]) # 인덱스로 접근
print(t[2:5], t[4:-1]) # 슬라이싱
print(t[:2], t[3:])

tensor(0.) tensor(1.) tensor(6.)
tensor([2., 3., 4.]) tensor([4., 5.])
tensor([0., 1.]) tensor([3., 4., 5., 6.])


In [15]:
# 2D with Pytorch
t = torch.FloatTensor([[1., 2., 3.],
                        [4., 5., 6.],
                        [7., 8., 9.],
                        [10, 11., 12.]
                        ])
print(t)

tensor([[ 1.,  2.,  3.],
        [ 4.,  5.,  6.],
        [ 7.,  8.,  9.],
        [10., 11., 12.]])


In [16]:
# dim() 을 사용하면 현재 텐서의 차원을 보여준다. size() 를 사용하면 크기 확인
print(t.dim()) # rank : 차원
print(t.size()) # shape

2
torch.Size([4, 3])


In [17]:
# 슬라이싱
print(t[:, 1]) # 첫번째 차원을 전체 선택한 상황에서 두번째 차원의 첫번째 것만 가져온다 인덱스[1]
print(t[:, 1].size()) # 위 경우의 크기

tensor([ 2.,  5.,  8., 11.])
torch.Size([4])


In [18]:
# 첫번째 차원을 전체 선택한 상황에서 두번째 차원에서는 맨 마지막에서 첫번째를 제외하고 다 가져오기
print(t[:, :-1])

tensor([[ 1.,  2.],
        [ 4.,  5.],
        [ 7.,  8.],
        [10., 11.]])


In [19]:
# 브로드캐스팅(Broadcasting)
# A, B 두 행렬이 곱셈을 할 때는 A 의 마지막 차원과 B의 첫번째 차원이 일치해야 한다
# 불가피하게 일치하지 않는 사칙 연산을 할 경우 자동으로 크기를 맞춰서 연산을 수행하게 하는 브로드캐스팅 사용
# 브로드캐스팅은 편리하지만, 사용자 입장에서 굉장히 주의해서 사용해야 한다

In [20]:
# 같은 크기일 때 연산
m1 = torch.FloatTensor([[3, 3]])
m2 = torch.FloatTensor([[2, 2]])
print(m1 + m2)

tensor([[5., 5.]])


In [21]:
# 크기가 다른 탠서간의 연산
# Vector + scalar
m1 = torch.FloatTensor([[1, 2]])
m2 = torch.FloatTensor([3]) # [3] -> [3, 3] ; m2 의 크기를 (1,) 에서 (1, 2) 로 변경하여 연산을 수행
print(m1 + m2)

tensor([[4., 5.]])


In [22]:
# 2 x 1 Vector + 1 X 2 Vector
m1 = torch.FloatTensor([[1, 2]])
m2 = torch.FloatTensor([[3], [4]])
print(m1 + m2)

tensor([[4., 5.],
        [5., 6.]])


In [ ]:
# 자주 사용되는 기능들

In [23]:
# 행렬 곱셈과 곱셈의 차이 (Matrix Multiplication Vs. MultiPlication)
# 행렬 곱셈 -> matmul()
m1 = torch.FloatTensor([[1, 2], [3, 4]])
m2 = torch.FloatTensor([[1], [2]])
print('Shape of Matrix 1: ', m1.shape) # 2 x 2
print('Shape of Matrix 2: ', m2.shape) # 2 x 1
print(m1.matmul(m2)) # 2 X 1

Shape of Matrix 1:  torch.Size([2, 2])
Shape of Matrix 2:  torch.Size([2, 1])
tensor([[ 5.],
        [11.]])


In [24]:
# element-wise 곱셈
# 동일한 크기의 행렬이 동일한 위치에 있는 원소끼리 곱하는 것
# 서로 다른 크기의 행렬이 브로드캐스팅 된 후 element-wise 곱셈이 수행되는 예 -> * 또는 mul()
m1 = torch.FloatTensor([[1, 2], [3, 4]])
m2 = torch.FloatTensor([[1], [2]])
print('Shape of Matrix 1: ', m1.shape) # 2 x 2
print('Shape of Matrix 2: ', m2.shape) # 2 x 1
print(m1 * m2) # 2 x 2
print(m1.mul(m2))

Shape of Matrix 1:  torch.Size([2, 2])
Shape of Matrix 2:  torch.Size([2, 1])
tensor([[1., 2.],
        [6., 8.]])
tensor([[1., 2.],
        [6., 8.]])


In [25]:
# 평균(Mean)
t = torch.FloatTensor([1, 2])
print(t.mean())

tensor(1.5000)


In [27]:
t = torch.FloatTensor([[1, 2], [3, 4]])
print(t)
print(t.mean())

tensor([[1., 2.],
        [3., 4.]])
tensor(2.5000)


In [30]:
# dim = 0 : 첫 번째 차원 의마
# 행렬에서의 첫 번쨰 차원 : '행' 의미
# 인자 dim = 0 -> 해당 차원 제거 ; 행렬에서 행 제거 후 열만 남김, 예) (2, 2) -> (1, 2)
# 실제 연산
print(t.mean(dim=0))
print(t.mean(dim=1))
print(t.mean(dim=-1))

tensor([2., 3.])
tensor([1.5000, 3.5000])
tensor([1.5000, 3.5000])


In [32]:
# 덧셈
t = torch.FloatTensor([[1, 2], [3, 4]])
print(t)
print(t.sum())
print(t.sum(dim=0))
print(t.sum(dim=1))
print(t.sum(dim=-1))

tensor([[1., 2.],
        [3., 4.]])
tensor(10.)
tensor([4., 6.])
tensor([3., 7.])
tensor([3., 7.])


In [33]:
# 최대(Max)와 아그맥스(ArgMax)
# 최대(Max) 는 원소의 최대값을 리턴, 아그맥스(ArgMax)는 최대값을 가진 인덱스를 리턴
t = torch.FloatTensor([[1, 2], [3, 4]])
print(t)
print(t.max())
print(t.max(dim=0)) # 최대값의 인덱스도 같이 리턴된다

tensor([[1., 2.],
        [3., 4.]])
tensor(4.)
torch.return_types.max(
values=tensor([3., 4.]),
indices=tensor([1, 1]))


In [34]:
print('Max: ', t.max(dim=0)[0])
print('ArgMax: ', t.max(dim=0)[1])

Max:  tensor([3., 4.])
ArgMax:  tensor([3., 4.])
