In [2]:
import numpy as np
import torch

In [3]:
# 뷰(View) - 원소의 수를 유지하면서 텐서의 크기 변경. 매우 중요!
# 넘파이의 Reshape 와 같은 엵할
t = np.array([[[0, 1, 2],
                [3, 4, 5]],
                [[6, 7, 8],
                [9, 10, 11]]])
ft = torch.FloatTensor(t)

print(ft.shape) # 텐서의 크기 : (2, 2, 3)

torch.Size([2, 2, 3])


In [4]:
# 3차원 텐서에서 2차원 텐서로 변경
# ft 텐서를 view 를 사용하여 크기(shape)를 2차원 텐서로 변경
print(ft.view([-1, 3])) # ft 텐서를 (?, 3) 의 크기로 변경 -> -1 은 사용자가 잘 모르겠으니 파이토치에게 맡김, 3 은 두 번째 차원의 크기 3
print(ft.view([-1, 3]).shape)

tensor([[ 0.,  1.,  2.],
        [ 3.,  4.,  5.],
        [ 6.,  7.,  8.],
        [ 9., 10., 11.]])
torch.Size([4, 3])


In [5]:
# view 규칙
# 변경 전과 변경 후의 테너 안에서 원소의 개수가 유지되어야 한다
# 파이토치의 view 는 사이즈가 -1 로 설정되면 다른 차원으로부터 해당 값을 유추

In [6]:
# 3차원 텐서의 크기 변경
# 3차원 텐서 -> 3차원 텐서로 차원 유지, 크기(shape) 바꾸는 작업
# (2 x 2 x 3) -> (? x 1 x 3) 으로 변경
print(ft.view([-1, 1, 3]))
print(ft.view([-1, 1, 3]).shape)

tensor([[[ 0.,  1.,  2.]],

        [[ 3.,  4.,  5.]],

        [[ 6.,  7.,  8.]],

        [[ 9., 10., 11.]]])
torch.Size([4, 1, 3])


In [7]:
# 스퀴즈(Squeeze) - 1인 차원을 제거
# 스퀴즈는 차원이 1인 경우에 해당 차원 제거
# 임의의 (3 x 1) 크기를 가지는 2차원 텐서 생성
ft = torch.FloatTensor([[0], [1], [2]])
print(ft)
print(ft.shape)

tensor([[0.],
        [1.],
        [2.]])
torch.Size([3, 1])


In [8]:
print(ft.squeeze())
print(ft.squeeze().shape)

tensor([0., 1., 2.])
torch.Size([3])


In [9]:
# 언스퀴즈(Unsqueeze) - 특정 위치에 1인 차원 추가
# 스퀴즈와 정반대, 특정 위치에 1인 차원 추가
ft = torch.Tensor([0, 1, 2]) # 차원이 1 인 1차원 벡터
print(ft.shape)

torch.Size([3])


In [10]:
print(ft.unsqueeze(0)) # 인덱스가 0부터 시작하므로 0 은 첫 번째 차원을 의미 (3,) -> (1 X 3)의 2차원 벡터
print(ft.unsqueeze(0).shape)

tensor([[0., 1., 2.]])
torch.Size([1, 3])


In [11]:
# view 로 구현 가능
print(ft.view(1, -1))
print(ft.view(1, -1).shape)

tensor([[0., 1., 2.]])
torch.Size([1, 3])


In [12]:
# unsqueeze 인자 1 -> 두 번째 차원에 1 추가
# (3,) -> (3, 1) 크기
print(ft.unsqueeze(1))
print(ft.unsqueeze(1).shape)

tensor([[0.],
        [1.],
        [2.]])
torch.Size([3, 1])


In [13]:
# unsqueeze 인자 -1 : 인덱스 상 마지막 차원
print(ft.unsqueeze(-1))
print(ft.unsqueeze(-1).shape)

tensor([[0.],
        [1.],
        [2.]])
torch.Size([3, 1])


In [14]:
# 타입 캐스팅(Type Casting) : 자료형 변환

# torch.FloatTensor : 32비트 부동소수점
# torch.LongTensor : 64비트 부동소수점
# torch.cuda.FloatTensor : GPU 연산

In [15]:
lt = torch.LongTensor([1, 2, 3, 4]) # long 타입 텐서 선언
print(lt)

tensor([1, 2, 3, 4])


In [16]:
print(lt.float()) # float 로 타입 변경

tensor([1., 2., 3., 4.])


In [17]:
bt = torch.ByteTensor([True, False, False, True]) # Byte 타입 텐서 선언
print(bt)

tensor([1, 0, 0, 1], dtype=torch.uint8)


In [18]:
print(bt.long()) # long 타입 텐서 변경
print(bt.float()) # float 타입 텐서 변경

tensor([1, 0, 0, 1])
tensor([1., 0., 0., 1.])


In [19]:
# 연결하기(Concatenate)
# 두 텐서를 연결하는 방법
x = torch.FloatTensor([[1, 2], [3, 4]])
y = torch.FloatTensor([[5, 6], [7, 8]])

# torch.cat([])를 통해 연결. 어느 차원을 늘릴 것인지 인자로 줄 수 있다. dim = 0 : 첫번째 차원
print(torch.cat([x, y], dim=0))

tensor([[1., 2.],
        [3., 4.],
        [5., 6.],
        [7., 8.]])


In [20]:
print(torch.cat([x, y], dim=1))

tensor([[1., 2., 5., 6.],
        [3., 4., 7., 8.]])


In [22]:
# 스택킹(Stacking)
# 연결(concatenate) 를 하는 또 다른 방법

x = torch.FloatTensor([1, 4])
y = torch.FloatTensor([2, 5])
z = torch.FloatTensor([3, 6])

# torch.stack 을 통해 3개의 벡터를 모두 스태킹
print(torch.stack([x, y, z]))
# 아래 계산과 동일한 작업
print(torch.cat([x.unsqueeze(0), y.unsqueeze(0), z.unsqueeze(0)], dim=0))

tensor([[1., 4.],
        [2., 5.],
        [3., 6.]])
tensor([[1., 4.],
        [2., 5.],
        [3., 6.]])


In [23]:
# dim=1 인자
print(torch.stack([x, y, z], dim=1))

tensor([[1., 2., 3.],
        [4., 5., 6.]])


In [24]:
# one_like 와 zeros_like : 1 로 채워진 텐서와 0 으로 채워진 텐서

x = torch.FloatTensor([[0, 1, 2], [2, 1, 0]])
print(x)

tensor([[0., 1., 2.],
        [2., 1., 0.]])


In [25]:
# one_like
print(torch.ones_like(x)) # 입력 텐서와 크기를 동일하게 하면서 값을 1로 채우기

tensor([[1., 1., 1.],
        [1., 1., 1.]])


In [26]:
# zeros_like
print(torch.zeros_like(x)) # 입력 텐서와 크기를 동일하게 하면서 값을 0 으로 채우기

tensor([[0., 0., 0.],
        [0., 0., 0.]])


In [27]:
# In-place Operation(덮어쓰기 연산)
x = torch.FloatTensor([[1, 2], [3, 4]])
# 곱하기 연산을 한 값과 기존 값 출력
print(x.mul(2.)) # 곱하기 2를 수행한 결과를 출력
print(x)

tensor([[2., 4.],
        [6., 8.]])
tensor([[1., 2.],
        [3., 4.]])


In [28]:
# 연산 뒤 _ 를 붙이면 기존 값 덮어쓰기
print(x.mul_(2.)) # 곱하기 2를 수행한 결과 변수 x에 값을 저장하면서 결과를 출력
print(x) # 기존의 값 출력

tensor([[2., 4.],
        [6., 8.]])
tensor([[2., 4.],
        [6., 8.]])
