In [1]:
# 04 nn.Module 로 구현하는 선형 회귀

# 파이토치에서 제공하는 함수를 불러오는 것으로 더 쉽게 선형 회귀 모델을 구현
# 선형 회귀 모델 : nn.Linear(), 평균 제곱오차 : nn.functional.mse_loss()

In [2]:
# 단순 선형 회귀 구현

# 필요 도구 임포트
import torch
import torch.nn as nn
import torch.nn.functional as F

torch.manual_seed(1)

In [3]:
# 데이터 선언 ( y = 2x 가정 )
x_train = torch.FloatTensor([[1], [2], [3]])
y_trian = torch.FloatTensor([[2], [4], [6]])

In [5]:
# 선형 회귀 모델 구현
# 모델을 선언 및 초기화. 단순 선형 회귀이므로 input_dim=1, output_dim = 1 : 하나의 입력 x 에 대해 하나의 출력 y 를 가짐 -> 입력, 출력 차원 1
model = nn.Linear(1, 1)

# model 에는 가중치 W 와 편향 b 가 저장되어 있음. model.parameters() 함수를 통해 불어올 수 있음, 두 파라미터는 랜덤 초기화 상태
print(list(model.parameters()))

[Parameter containing:
tensor([[0.5153]], requires_grad=True), Parameter containing:
tensor([-0.4414], requires_grad=True)]


In [6]:
# 옵티마이저 정의. model.parameters() 를 사용하여 W 와 b를 전달, 학습률은 0.01로 정한다
# optimizer 설정. 경사 하강법 SGD를 사용하고 learning rate를 의미하는 lr은 0.01
optimizer = torch.optim.SGD(model.parameters(), lr=0.01)

In [7]:
# 전체 훈련 데이터에 대해 경사 하강법을 2000 회 반복
nb_epochs = 2000
for epoch in range(nb_epochs+1):

    # H(x) 계산
    prediction = model(x_train)

    # cost 계산
    cost = F.mse_loss(prediction, y_trian) # 파이토치에서 제공하는 평균 제곱 오차 함수

    # cost 로 H(x) 개선
    # gradient 를 0 으로 초기화
    optimizer.zero_grad()
    # 비용 함수를 미분하여 gradient 계산
    cost.backward()
    # W 와 b 를 업데이트
    optimizer.step()

    # 100번 마다 로그 출력
    if epoch % 100 == 0:
        print('Epoch {:4d}/{} Cost: {:.6f}'.format(epoch, nb_epochs, cost.item()))

Epoch    0/2000 Cost: 13.103541
Epoch  100/2000 Cost: 0.002791
Epoch  200/2000 Cost: 0.001724
Epoch  300/2000 Cost: 0.001066
Epoch  400/2000 Cost: 0.000658
Epoch  500/2000 Cost: 0.000407
Epoch  600/2000 Cost: 0.000251
Epoch  700/2000 Cost: 0.000155
Epoch  800/2000 Cost: 0.000096
Epoch  900/2000 Cost: 0.000059
Epoch 1000/2000 Cost: 0.000037
Epoch 1100/2000 Cost: 0.000023
Epoch 1200/2000 Cost: 0.000014
Epoch 1300/2000 Cost: 0.000009
Epoch 1400/2000 Cost: 0.000005
Epoch 1500/2000 Cost: 0.000003
Epoch 1600/2000 Cost: 0.000002
Epoch 1700/2000 Cost: 0.000001
Epoch 1800/2000 Cost: 0.000001
Epoch 1900/2000 Cost: 0.000000
Epoch 2000/2000 Cost: 0.000000


In [8]:
# 학습 완료 후 W 와 b 값이 최적화가 되었는지 확인
# x 에 임의의 값 4를 넣어 모델이 예측하는 y 의 값을 확인

# 임의의 입력값 4를 선언
new_var = torch.FloatTensor([[4.0]])

# 입력한 값 4에 대해 예측값 y를 리턴받아 pred_y 에 저장
pred_y = model(new_var) # forward 연산

# y = 2x 이므로 입력이 4라면 y가 8에 가까운 값이 나와야 제대로 학습된 것
print("훈련 후 입력이 4일 때 예측 값 : ", pred_y)

훈련 후 입력이 4일 때 예측 값 :  tensor([[7.9989]], grad_fn=<AddmmBackward0>)


In [9]:
# 학습 후 W 와 b 출력
print(list(model.parameters()))

[Parameter containing:
tensor([[1.9994]], requires_grad=True), Parameter containing:
tensor([0.0014], requires_grad=True)]


In [10]:
# 다중 선형 회귀 구현하기
# 코드 자체는 거의 같다

In [24]:
# 데이터 선언, 3개의 x로부터 하나의 y를 예측하는 문제
# 가설 수식은 H(x) = w1*x1 + w2*x2 + w3*x3 + b

# 데이터 선언
x_train = torch.FloatTensor([[73, 80, 75],
                            [93, 88, 93],
                            [89, 91, 90],
                            [96, 98, 100],
                            [73, 66, 70]])
y_train = torch.FloatTensor([[152], [185], [180], [196], [142]])

In [25]:
# 모델을 선언 및 초기화. 다중 선형 회귀이므로 input_dim = 3, output_dim = 1
model = nn.Linear(3, 1)
print(list(model.parameters()))

[Parameter containing:
tensor([[ 0.5047,  0.1797, -0.2150]], requires_grad=True), Parameter containing:
tensor([-0.3487], requires_grad=True)]


In [26]:
# 
optimizer = torch.optim.SGD(model.parameters(), lr=1e-5)

nb_epochs = 2000
for epoch in range(nb_epochs+1):

    # H(x)
    prediction = model(x_train)
    # model(x_train) 은 model.forward(x_train) 과 동일

    # cost
    cost = F.mse_loss(prediction, y_train)

    # cost 로 H(x) 계산
    optimizer.zero_grad()
    cost.backward()
    optimizer.step()

    # 100번 마다 로그 출력
    if epoch % 100 == 0:
        print('Epoch {:4d}/{} Cost: {:.6f}'.format(epoch, nb_epochs, cost.item()))

Epoch    0/2000 Cost: 17620.488281
Epoch  100/2000 Cost: 0.574603
Epoch  200/2000 Cost: 0.554116
Epoch  300/2000 Cost: 0.534724
Epoch  400/2000 Cost: 0.516340
Epoch  500/2000 Cost: 0.498923
Epoch  600/2000 Cost: 0.482425
Epoch  700/2000 Cost: 0.466791
Epoch  800/2000 Cost: 0.451984
Epoch  900/2000 Cost: 0.437960
Epoch 1000/2000 Cost: 0.424665
Epoch 1100/2000 Cost: 0.412076
Epoch 1200/2000 Cost: 0.400147
Epoch 1300/2000 Cost: 0.388840
Epoch 1400/2000 Cost: 0.378133
Epoch 1500/2000 Cost: 0.367990
Epoch 1600/2000 Cost: 0.358375
Epoch 1700/2000 Cost: 0.349267
Epoch 1800/2000 Cost: 0.340636
Epoch 1900/2000 Cost: 0.332464
Epoch 2000/2000 Cost: 0.324713


In [27]:
# 학습 완료 후 W 와 b 값이 최적화가 되었는지 확인
# x 에 임의의 값 4를 넣어 모델이 예측하는 y 의 값을 확인

# 임의의 입력값 [73, 80, 75]를 선언
new_var = torch.FloatTensor([[73, 80, 75]])

# 입력한 값 4에 대해 예측값 y를 리턴받아 pred_y 에 저장
pred_y = model(new_var) # forward 연산

# y = 2x 이므로 입력이 4라면 y가 8에 가까운 값이 나와야 제대로 학습된 것
print("훈련 후 입력이 73, 80, 75일 때 예측 값 : ", pred_y)

훈련 후 입력이 73, 80, 75일 때 예측 값 :  tensor([[152.1337]], grad_fn=<AddmmBackward0>)


In [28]:
# 학습 후 W 와 b 값
print(list(model.parameters()))

[Parameter containing:
tensor([[1.0619, 0.6366, 0.3205]], requires_grad=True), Parameter containing:
tensor([-0.3422], requires_grad=True)]
