In [1]:
# nn.Module 로 구현하는 로지스틱 회귀

# nn.Sigmoid()를 통하여 시그모이드 함수 구현

In [5]:
import torch
import torch.nn as nn
import torch.nn.functional as F
import torch.optim as optim

torch.manual_seed(1)

In [6]:
# 훈련 데이터 텐서로 선언
x_data = [[1, 2], [2, 3], [3, 1], [4, 3], [5, 3], [6, 2]]
y_data = [[0], [0], [0], [1], [1], [1]]
x_train = torch.FloatTensor(x_data)
y_train = torch.FloatTensor(y_data)

In [7]:
# nn.Sequential() : nn.Module 층을 차례로 쌓을 수 있다
# 이를 이용하여 인공 신겨앙 구현 -> nn.Sequential 은 여러 함수들을 연결해주는 역할

model = nn.Sequential(
    nn.Linear(2, 1), # input_dim = 2, output_dim = 1
    nn.Sigmoid() # 출력은 시그모이드 함수를 거친다
)

In [8]:
# W 와 b 는 랜덤 초기화가 된 상태, 훈련 데이터를 넣어 예측값 확인 
model(x_train)

tensor([[0.4020],
        [0.4147],
        [0.6556],
        [0.5948],
        [0.6788],
        [0.8061]], grad_fn=<SigmoidBackward0>)

In [12]:
# 경사 하강법을 이용해 훈련, 100 번의 에포크

# optimizer 설정
optimizer = optim.SGD(model.parameters(), lr=1)

nb_epochs = 1000
for epoch in range(nb_epochs+1):

    # H(x) 계산
    hypothesis = model(x_train)

    # cost 계산
    cost = F.binary_cross_entropy(hypothesis, y_train)

    # cost 로 H(x) 계산
    optimizer.zero_grad()
    cost.backward()
    optimizer.step()

    # 20번 마다 로그 출력
    if epoch % 20 == 0:
        prediction = hypothesis >= torch.FloatTensor([0.5]) # 예측값이 0.5를 넘으면 True 로 간주
        correct_prediction = prediction.float() == y_train # 실제값과 일치하는 경우에만 True 로 간주
        accuracy = correct_prediction.sum().item() / len(correct_prediction) # 정확도를 계산

        print('Epoch {:4d}/{} Cost: {:.6f} Accuracy {:2.2f}'.format(epoch, nb_epochs, cost.item(), accuracy * 100))

Epoch    0/1000 Cost: 0.006957 Accuracy 100.00
Epoch   20/1000 Cost: 0.006912 Accuracy 100.00
Epoch   40/1000 Cost: 0.006868 Accuracy 100.00
Epoch   60/1000 Cost: 0.006824 Accuracy 100.00
Epoch   80/1000 Cost: 0.006781 Accuracy 100.00
Epoch  100/1000 Cost: 0.006739 Accuracy 100.00
Epoch  120/1000 Cost: 0.006697 Accuracy 100.00
Epoch  140/1000 Cost: 0.006655 Accuracy 100.00
Epoch  160/1000 Cost: 0.006614 Accuracy 100.00
Epoch  180/1000 Cost: 0.006574 Accuracy 100.00
Epoch  200/1000 Cost: 0.006534 Accuracy 100.00
Epoch  220/1000 Cost: 0.006494 Accuracy 100.00
Epoch  240/1000 Cost: 0.006455 Accuracy 100.00
Epoch  260/1000 Cost: 0.006417 Accuracy 100.00
Epoch  280/1000 Cost: 0.006379 Accuracy 100.00
Epoch  300/1000 Cost: 0.006341 Accuracy 100.00
Epoch  320/1000 Cost: 0.006304 Accuracy 100.00
Epoch  340/1000 Cost: 0.006267 Accuracy 100.00
Epoch  360/1000 Cost: 0.006231 Accuracy 100.00
Epoch  380/1000 Cost: 0.006195 Accuracy 100.00
Epoch  400/1000 Cost: 0.006159 Accuracy 100.00
Epoch  420/10

In [13]:
# 기존의 훈련 데이터를 입력하여 예측값 확인
model(x_train)

tensor([[1.0163e-05],
        [8.7004e-03],
        [1.0270e-02],
        [9.8776e-01],
        [9.9987e-01],
        [9.9999e-01]], grad_fn=<SigmoidBackward0>)

In [14]:
# 훈련 후 W 와 b의 값 출력
print(list(model.parameters()))

[Parameter containing:
tensor([[4.5632, 2.1979]], requires_grad=True), Parameter containing:
tensor([-20.4557], requires_grad=True)]
